---
title: Wat is vochtigheid?
hero_image: images/banner.png
description: Kom alles te weten over vochtigheid
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
duration: 1 #1, 2 or 3
ingredient: true
listed: false
copyedit: false
interests:
technologies:
steps:
  - title: Wat is vochtigheid?
