---
title: O que é a humidade?
hero_image: images/banner.png
description: Descubre tudo sobre a humidade
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
duration: 1 #1, 2 or 3
ingredient: true
listed: false
copyedit: false
interests:
technologies:
steps:
  - 
    title: O que é a humidade?
