---
title: Kaj je vlaga?
hero_image: images/banner.png
description: Poiščite vse o vlagi
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
duration: 1 #1, 2 or 3
ingredient: true
listed: false
copyedit: false
interests:
technologies:
steps:
  - 
    title: Kaj je vlaga?
