---
title: Mi az a p치ratartalom?
hero_image: images/banner.png
description: Tudj meg mindent a p치ratartalomr칩l
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
duration: 1 #1, 2 or 3
ingredient: true
listed: false
copyedit: false
interests:
technologies:
steps:
  - title: Mi az a p치ratartalom?
