---
title: Qu'est-ce que l'humidité ?
hero_image: images/banner.png
description: Tout savoir sur l'humidité
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
duration: 1 #1, 2 or 3
ingredient: true
listed: false
copyedit: false
interests:
technologies:
steps:
  - title: Qu'est-ce que l'humidité ?
